# Generated by Django 5.0.6 on 2024-07-30 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tecnoburguer.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tecnoburguer.order')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locale', models.CharField(max_length=255)),
                ('admins', models.ManyToManyField(limit_choices_to={'type': 'admin'}, related_name='admin_stores', to=settings.AUTH_USER_MODEL)),
                ('employees', models.ManyToManyField(limit_choices_to={'type': 'employee'}, related_name='employee_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='tecnoburguer.store'),
        ),
        migrations.AddField(
            model_name='food',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='tecnoburguer.store'),
        ),
        migrations.CreateModel(
            name='StoreHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.TimeField()),
                ('monday_close', models.TimeField()),
                ('tuesday_open', models.TimeField()),
                ('tuesday_close', models.TimeField()),
                ('wednesday_open', models.TimeField()),
                ('wednesday_close', models.TimeField()),
                ('thursday_open', models.TimeField()),
                ('thursday_close', models.TimeField()),
                ('friday_open', models.TimeField()),
                ('friday_close', models.TimeField()),
                ('saturday_open', models.TimeField()),
                ('saturday_close', models.TimeField()),
                ('sunday_open', models.TimeField()),
                ('sunday_close', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='tecnoburguer.store')),
            ],
        ),
    ]
