# Generated by Django 5.0.6 on 2024-07-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0002_food_order_orderitem_store_order_store_food_store_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreHours',
            new_name='StoreHour',
        ),
    ]
