# Generated by Django 5.0.6 on 2024-07-30 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0003_rename_storehours_storehour'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='states',
            field=models.CharField(choices=[('avaliable', 'Disponível'), ('unavaliable', 'Indisponível')], default='avaliable', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='name_store',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='states',
            field=models.CharField(choices=[('open', 'Aberta'), ('close_today', 'Fechada hoje'), ('close_temporarily', 'Fechada temporariamente'), ('close_permanently', 'Fechada permanentemente')], default='open', max_length=17),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='tecnoburguer.store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tecnoburguer.food'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='tecnoburguer.order'),
        ),
    ]
