# Generated by Django 5.0.6 on 2024-07-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0004_food_states_order_name_store_store_states_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('sudo', 'Superuser'), ('admin', 'Administrador'), ('attendant', 'Atendente'), ('cashier', 'Caixa'), ('chef', 'Cozinheiro'), ('deliveryman', 'Entregador'), ('client', 'Cliente')], default='client', max_length=11),
        ),
    ]
