# Generated by Django 5.0.6 on 2024-07-31 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0006_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='employees',
            field=models.ManyToManyField(limit_choices_to={'type': 'attendant'}, related_name='employee_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
