# Generated by Django 5.0.6 on 2024-08-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0007_alter_store_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='states',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='states',
            new_name='state',
        ),
    ]
