# Generated by Django 5.0.6 on 2024-08-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0008_rename_states_food_state_rename_states_store_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='min_order',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='rate_km',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=6),
            preserve_default=False,
        ),
    ]
