# Generated by Django 5.0.6 on 2024-08-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0009_store_min_order_store_rate_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_free_km',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('sudo_main', 'Superuser geral'), ('sudo', 'Superuser'), ('admin', 'Administrador'), ('attendant', 'Atendente'), ('cashier', 'Caixa'), ('chef', 'Cozinheiro'), ('deliveryman', 'Entregador'), ('client', 'Cliente')], default='client', max_length=11),
        ),
    ]
