# Generated by Django 5.0.6 on 2024-08-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0014_assessments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assessments',
            new_name='Assessment',
        ),
    ]
