# Generated by Django 5.0.6 on 2024-08-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0015_rename_assessments_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
