# Generated by Django 5.0.6 on 2024-08-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0016_alter_assessment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
