# Generated by Django 5.0.6 on 2024-08-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0017_alter_assessment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
