# Generated by Django 5.0.6 on 2024-08-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0018_alter_assessment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.BinaryField(),
        ),
    ]
