# Generated by Django 5.0.6 on 2024-08-16 01:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0020_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='foods/'),
        ),
    ]
