# Generated by Django 5.0.6 on 2024-08-22 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0026_alter_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='delivery_free_km',
        ),
        migrations.RemoveField(
            model_name='store',
            name='rate_km',
        ),
        migrations.CreateModel(
            name='InfosDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_free_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preparation_time', models.IntegerField()),
                ('delivery_time_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos_delivery', to='tecnoburguer.store')),
            ],
        ),
    ]
