# Generated by Django 5.0.6 on 2024-08-23 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0027_remove_store_delivery_free_km_remove_store_rate_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosdelivery',
            name='delivery_time_km',
        ),
        migrations.RemoveField(
            model_name='infosdelivery',
            name='preparation_time',
        ),
    ]
