# Generated by Django 5.0.6 on 2024-08-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoburguer', '0028_remove_infosdelivery_delivery_time_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosdelivery',
            name='max_delivery_time_km',
            field=models.DecimalField(decimal_places=2, default=35, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infosdelivery',
            name='max_preparation_time',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infosdelivery',
            name='min_delivery_time_km',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infosdelivery',
            name='min_preparation_time',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
