# Generated by Django 5.0.6 on 2024-07-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('stock', models.IntegerField()),
                ('status', models.CharField(choices=[('Avaliable', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=12)),
            ],
        ),
    ]
